cc_binary(
    name = "butter2sos",
    srcs = ["butter2sos.c"],
    deps = [
        "//lib:butterlib"
    ],
)

cc_binary(
    name = "butterband",
    srcs = ["butterband.c"],
    deps = [
        "//lib:butterlib"
    ],
)