cc_binary(
    name = "butter2sos",
    srcs = ["butter2sos.c"],
    deps = ["//lib:design"],
    copts = ["-Ilib/"],
)

cc_binary(
    name = "butterband",
    srcs = ["butterband.c"],
    deps = ["//lib:design"],
    copts = ["-Ilib/"],
)