name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI Bazel build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v2
      - run: bazel build //...

  wheel-build:
    name: pip wheel test
    runs-on: ubuntu-latest
    needs: ci
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Copy DLL to package
        run: ./scripts/copy_lib.sh
      - name: Build wheel
        run: ./scripts/pip_install.sh
      - name: Run pytest
        run: ./scripts/run_tests.sh