name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI Bazel build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run the bazel build
        run: bazel build //...
      - name: Copy DLL to package
        run: ./ci/copy_lib.sh
      - name: Build and install the wheel
        run: ./ci/pip_install.sh
      - name: Run pytest
        run: ./ci/run_tests.sh